### PR TITLE
ML-637: Add Malay Profile

### PR DESCRIPTION
**Pull request by rosequ**
Why was this PR opened?
The existing codebases lacks support for Malay (ms) language.

What are the changes?
Added the Malay language profile.

How can someone test the changes?
python setup.py install

On a Python interpreter:
```bash
>>> from langdetect import detect_langs
>>> detect_langs("Terima Kasih Berbanyak-Banyak")
[ms:0.9999924459211373]
```
---
- [x] PR description present and accurate
- [x] Code changes are documented
~- [ ] Unit tests cover code changes~
~- [ ] PR was tested on ada-dev~
- [x] PR title follows the format \<Jira Card\>: \<Change description\>
~- [] Deployment plan is included in PR if required~

### CODE REVIEW

**Comment by rosequ** [comment]
Once this PR is merged, we will have to change the commit id in the `AM` requirements file @gordania.

**Review by gordania — APPROVED** [review]
Would be curious to know how this affects the results in the export 👀

**Comment by rosequ** [comment]
Yes, I'm planning on finishing those analysis before our meeting!

**Comment by gordania** [comment]
> Yes, I'm planning on finishing those analysis before our meeting!

Wonderful !!

**Pull request merged**
